### ISSUE TITLE
안녕하세요. 장인의 길 모임에 저도 참여 할 수 있을까요?

### ISSUE THREAD

**Issue by jongfeel** [road-of-craftsman/study-elegant-object#44]
안녕하세요.

저는 버넥트라는 회사에서 일하고 있는 개발자 김종필입니다.

github의 알 수 없는 알고리즘이 이 repository를 추천해 줬고
둘러보니까 책 선정도 좋은 것 같고 pull request도 다들 열심히 하시는 것 같아서 좋아 보입니다.

저도 참여할 수 있을까요?

**Comment by Frankle97** [comment]
@jongfeel 
안녕하세요! 프로필의 이메일 주소로 메일 보내드렸습니다, 확인 부탁드릴게요!

**Comment by Frankle97** [comment]
join
